FROM python:3.14-slim

RUN useradd -m app

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY --chown=app:app . .

USER app

EXPOSE 8000

CMD ["gunicorn", "app.app:app", "--workers", "4", "--bind", "0.0.0.0:8000"]