name: CI/CD

on:
  push:
    branches:
        - main

jobs:
  ci-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Cloning
        uses: actions/checkout@v4

      - name: Installing Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
        
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8
          echo -e "[flake8]\nmax-line-length = 88\nextend-ignore = E203, W503" > .flake8

      - name: Running black
        run: python -m black --check src

      - name: Running flake8
        run: python -m flake8 src

# TODO: finish 
  ci-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Cloning
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Installing dependencies
        run: npm ci

      - name: Running ESLint
        run: npm run lint .

      - name: Running Prettier
        run: npm run format:check
